apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  type: NodePort
  selector:
    app: eureka
  ports:
    - port: 8761       # Service port inside the cluster
      targetPort: 8761 # Container port
      nodePort: 30061  # External port to access via Node IP

